apiVersion: v1
kind: ConfigMap
metadata:
  name: tileserver-envoy-config
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 9901
    
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              codec_type: AUTO
              
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                  log_format:
                    json_format:
                      start_time: "%START_TIME%"
                      method: "%REQ(:METHOD)%"
                      path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                      response_code: "%RESPONSE_CODE%"
                      user: "%DYNAMIC_METADATA(envoy.filters.http.jwt_authn:jwt_payload:sub)%"

              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: local_service
              
              http_filters:
              # JWT Authentication
              - name: envoy.filters.http.jwt_authn
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                  providers:
                    keycloak:
                      # Issuer must match the token exactly (usually external URL)
                      issuer: "https://keycloak.mustaci.com/realms/barbershop-realm"
                      audiences:
                      - "barbershop-app"
                      remote_jwks:
                        http_uri:
                          # Internal URL to fetch keys (faster, stays in cluster)
                          uri: "http://keycloak.database.svc.cluster.local/realms/barbershop-realm/protocol/openid-connect/certs"
                          cluster: keycloak_cluster
                          timeout: 5s
                        cache_duration:
                          seconds: 300
                      forward: true
                      payload_in_metadata: jwt_payload
                      from_headers:
                      - name: Authorization
                        value_prefix: "Bearer "
                  rules:
                  - match:
                      prefix: "/"
                    requires:
                      provider_name: "keycloak"


              # RBAC
              # - name: envoy.filters.http.rbac
              #   typed_config:
              #     "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
              #     rules:
              #       action: ALLOW
              #       policies:
              #         "map-access":
              #           permissions:
              #             - any: true
              #           principals:
              #             - metadata:
              #                 filter: envoy.filters.http.jwt_authn
              #                 path:
              #                   - key: jwt_payload
              #                   - key: realm_access
              #                   - key: roles
              #                 value:
              #                   list_match:
              #                     one_of:
              #                       string_match:
              #                         exact: "map-viewer"
              #             - metadata:
              #                 filter: envoy.filters.http.jwt_authn
              #                 path:
              #                   - key: jwt_payload
              #                   - key: realm_access
              #                   - key: roles
              #                 value:
              #                   list_match:
              #                     one_of:
              #                       string_match:
              #                         exact: "admin"


              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      
      clusters:
      - name: local_service
        connect_timeout: 5s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: local_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: localhost
                    port_value: 8080
      
      - name: keycloak_cluster
        connect_timeout: 5s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: keycloak_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: keycloak.database.svc.cluster.local
                    port_value: 80
