apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tileserver-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - tiles.mustaci.com
    secretName: tiles-tls
  rules:
  - host: tiles.mustaci.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tileserver
            port:
              number: 80
