apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scraper-ingress
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - places-scraper.mustaci.com
    secretName: api-tls
  rules:
  - host: places-scraper.mustaci.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: places-scraper
            port:
              number: 80
